cluster {
  cluster-name = "socket-edge-cluster"
  jgroup-path = "/conf/jgroups.xml"

  role {
    prefer = master   # master | slave | auto
    strict = false    # kalau true & master sudah ada → FAIL
  }

  members = [
    "13.131.9.162",
    "13.131.9.166"
  ]

  jgroup = {
    bind-addr = "13.131.9.162"
    port = 7800
  }

  hazelcast = {
    port = 5701
  }
}
