server {
  name = ""
  port = 0
}

message {
  standard = ""
  packager {
    path = ""
    key = ""
  }
}

engine {
  cache {
    type = ""
    ttl = 0
  }

  seda {
    receive {
      consumers = 0
      queue-size = 0
      block-when-full = false
    }
    inbound {
      consumers = 0
      queue-size = 0
      block-when-full = false
    }
    outbound {
      consumers = 0
      queue-size = 0
      block-when-full = false
    }
  }
}